Squashed 'docker/' changes from a31a9bc5..7dd6bee3
7dd6bee3 refactore(docker): move Debian desktop-x and flutter specific configuration under debian folder
de1fed17 refactor(python): add Python support for Debian and update related configurations
6c7f90b1 refactor(naming) update project naming conventions to use 'vegito' prefix across Docker configurations
e8103ab9 feat(docker): add TARGETPLATFORM argument to Dockerfiles for improved build flexibility
f6d48f97 feat(docker): add Python Docker image support and update related configurations
e5ddfe65 refactor(naming): variable names and update Docker configurations to use VEGITO prefix
79323f36 feat(docker): add symlink to use bash as default shell
f341003e feat(docker): refactor Makefile and scripts for consistent Docker image handling
44ff8fe1 feat(docker): update Dockerfile and scripts for improved user management and GPU handling
c9ed7f54 feat(docker): add Dockerfile and docker-bake.hcl for Flutter on Debian
e57bcfcf feat(docker): add Dockerfile and docker-bake.hcl for Debian image setup and caching
590bdfb3 feat(docs): enrich README with detailed repository information and goals
028b886a feat(workflows): add reusable version changelog and build images workflows
REVERT: a31a9bc5 feat(docs): enrich README with detailed repository information and goals
REVERT: 9b5309b1 feat(workflows): add reusable version changelog and build images workflows

git-subtree-dir: docker
git-subtree-split: 7dd6bee301862075514e3c9e5880f9e539cacc93

diff --git a/.github/workflows/build-foundation-images.yml b/.github/workflows/build-foundation-images.yml
--- a/.github/workflows/build-foundation-images.yml
+++ b/.github/workflows/build-foundation-images.yml
@@ -33,10 +33,6 @@ on:
         required: false
         type: string
         default: "dockerhub runners builders services applications"
-      dockerhub_replica_version:
-        required: false
-        type: string
-        default: "latest"
       docker_registry_mode:
         required: false
         type: string
@@ -65,7 +61,7 @@ jobs:
     runs-on: self-hosted
     environment: ${{ inputs.environment }}
     env:
-      VEGITO_PROJECT_NAME: local-${{ inputs.environment }}-${{ github.ref_name }}-${{ github.run_id }}
+      VEGITO_PROJECT_NAME: vegito-${{ inputs.environment }}-${{ github.ref_name }}-${{ github.run_id }}
       VEGITO_PROJECT_USER: gha-${{ github.run_id }}-${{ inputs.environment }}
       VERSION: ${{ inputs.version }}
       GOOGLE_CLOUD_PROJECT_ID: ${{ secrets.GOOGLE_CLOUD_PROJECT_ID }}
@@ -134,12 +130,12 @@ jobs:
         run: |
           make gcloud-config-set-project
           make gcloud-auth-docker
-          make local-docker-buildx-setup
+          make vegito-docker-buildx-setup
 
       - name: Build Docker image
         env:
-          LOCAL_DOCKER_BUILDX_CI_BUILD_GROUPS: ${{ inputs.images_ci_build_groups }}
-          DOCKERHUB_REPLICA_VERSION: ${{ inputs.dockerhub_replica_version }}
+          VEGITO_DOCKER_BUILDX_CI_BUILD_GROUPS: ${{ inputs.images_ci_build_groups }}
+          VERSION: ${{ inputs.version }}
         run: |
           set -o pipefail
           make images-ci 2>&1 | tee images-build.log
@@ -153,9 +149,9 @@ jobs:
       - name: Generate docker image tag list for ${{ inputs.environment }}
         id: docker_tags
         run: |
-          make docker-tags-md-ci > docker-tags.md
-          if ! gcloud storage cp docker-tags.md gs://${{ env.VEGITO_RELEASE_BUCKET }}/${{ inputs.version }}/docker-tags.md; then
-            echo "::warning::failed to upload docker-tags.md"
+          make vegito-docker-tags-md-ci > vegito-docker-tags.md
+          if ! gcloud storage cp vegito-docker-tags.md gs://${{ env.VEGITO_RELEASE_BUCKET }}/${{ inputs.version }}/docker-tags.md; then
+            echo "::warning::failed to upload vegito-docker-tags.md"
           fi
 
       - name: Generate metadata.json and QR code
